name: build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [debug]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Linux Install
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libwayland-dev libxkbcommon-dev freeglut3-dev

    - name: Windows Install
      if: startsWith(matrix.os, 'windows')
      uses: bus1/cabuild/action/msdevshell@v1
      with:
        architecture: x64

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python Dependencies
      run: pip install meson ninja

    - name: Setup MacOS
      if: startsWith(matrix.os, 'macos')
      run: meson setup .build --buildtype=${{ matrix.build_type }} --cross-file=macos.txt

    - name: Setup Others
      if: not startsWith(matrix.os, 'macos')
      run: meson setup .build --buildtype=${{ matrix.build_type }}
      
    - name: Compile
      run: meson compile -v -C .build

    - name: Test
      run: meson test -v -C .build