name: build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [debug, release]
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Install
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libwayland-dev libxkbcommon-dev

    - name: Prepare MSVC
      if: matrix.os == 'windows-latest'
      uses: bus1/cabuild/action/msdevshell@v1
      with:
        architecture: x64

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python Dependencies
      run: pip install meson ninja

    - name: Setup
      run: meson setup .build --buildtype=${{ matrix.build_type }}
      
    - name: Compile
      run: meson compile -v -C .build

    - name: Test
      run: meson test -v -C .build