name: clang-format

on: [push]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: clang-format lint
      uses: DoozyX/clang-format-lint-action@v0.16.2
      with:
        source: './dubu-block'
        clangFormatVersion: 16
        inplace: true

    - name: Add & Commit
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        pull: "--rebase --autostash"
        message: "Formatted files using clang-format"